### ISSUE TITLE
Listing fields days

### ISSUE THREAD

**Issue by nathanjameshill** [pablo-libre/reefwatch-backend#2]
**When executing the following rest request:**
GET http://0.0.0.0:3001/field_days

**When fields_days collection contains:**
{ "_id" : ObjectId("5731a448a4aead046b70a3de"), "date" : "2016-03-12", "location" : "2000", "description" : "Hello" }

**I get the following response:**
<html>
    <title>500: Internal Server Error</title>
    <body>500: Internal Server Error</body>
</html>

**And the log file contains:**
HTTPServerRequest(protocol='http', host='0.0.0.0:3001', method='GET', uri='/field_days', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '0.0.0.0:3001', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Postman-Token': '8929fecd-a338-9ec6-484f-050191cc6bf6'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-4.3-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1445, in _execute
    result = yield result
  File "/Library/Python/2.7/site-packages/tornado-4.3-py2.7-macosx-10.9-intel.egg/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Library/Python/2.7/site-packages/tornado-4.3-py2.7-macosx-10.9-intel.egg/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Library/Python/2.7/site-packages/tornado-4.3-py2.7-macosx-10.9-intel.egg/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/Users/nathanjameshill/Projects/reefwatch-backend/fieldDayHandler.py", line 50, in get
    self.finish({"data": fieldDayList})
  File "/Library/Python/2.7/site-packages/tornado-4.3-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 906, in finish
    self.write(chunk)
  File "/Library/Python/2.7/site-packages/tornado-4.3-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 692, in write
    chunk = escape.json_encode(chunk)
  File "/Library/Python/2.7/site-packages/tornado-4.3-py2.7-macosx-10.9-intel.egg/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('5731a448a4aead046b70a3de') is not JSON serializable
2016-05-10 18:44:35,309: tornado.access - ERROR - 500 GET /field_days (127.0.0.1) 146.57ms

**Comment by pablo-libre** [comment]
Thanks for posting the issue with plenty of details.

It appears to be a JSON serialisation issue with the ObjectId(). I'll get working on a fix.

**Comment by nathanjameshill** [comment]
Fix working a treat. Thanks buddy.
